import type { Citation, Dossier, DossierSummary, DocumentRecord, FindingDetail, GraphData } from '../types'

const bankCitation: Citation = { id: 'cit-bank-1', documentId: 'doc-bank', documentName: 'Bank_confirmation_2023.pdf', page: 2, quote: 'Account DE89 3704 0044 0532 0130 00 · Balance as of 31 December 2023: EUR 18,420,000', boundingBox: { x: 8, y: 35, width: 83, height: 8 } }
const invoiceCitation: Citation = { id: 'cit-inv-1', documentId: 'doc-invoice', documentName: 'Invoice_MPS-1048.pdf', page: 1, quote: 'Payable to: DE89 3704 0044 0532 0130 00 · Total EUR 2,480,000', boundingBox: { x: 8, y: 62, width: 82, height: 9 } }
const vendorCitation: Citation = { id: 'cit-vendor-1', documentId: 'doc-vendor', documentName: 'Vendor_master_export.pdf', page: 4, quote: 'Northstar Consulting GmbH · IBAN DE89 3704 0044 0532 0130 00', boundingBox: { x: 7, y: 47, width: 86, height: 8 } }
const ledgerCitation: Citation = { id: 'cit-ledger-1', documentId: 'doc-ledger', documentName: 'General_ledger_Q4.xlsx.pdf', page: 7, quote: '31.12.2023 Cash and cash equivalents EUR 14,220,000', boundingBox: { x: 6, y: 53, width: 88, height: 8 } }

export const dossiers: Dossier[] = [{ id: 'meridian-2023', name: 'Meridian Payments · FY 2023', company: 'Meridian Payment Solutions GmbH', period: '01 Jan – 31 Dec 2023', status: 'ready', progress: 100 }]
export const summary: DossierSummary = { health: 62, documents: 20, verifiedFindings: 3, reviewQueue: 4, unresolvedEntities: 6, lastUpdated: 'Today, 14:32' }
export const documents: DocumentRecord[] = [
  { id: 'doc-bank', name: 'Bank_confirmation_2023.pdf', type: 'Bank confirmation', language: 'EN', pages: 3, status: 'verified', extractedFacts: 18, previewLines: ['FIRST MERCHANT BANK', 'Account confirmation', 'To whom it may concern', '', bankCitation.quote, '', 'The account named above is held in trust', 'for Meridian Payment Solutions GmbH.', '', 'Signed: 04 January 2024', 'Corporate Banking Services'] },
  { id: 'doc-invoice', name: 'Invoice_MPS-1048.pdf', type: 'Invoice', language: 'EN', pages: 1, status: 'verified', extractedFacts: 12, previewLines: ['NORTHSTAR CONSULTING', 'INVOICE MPS-1048', '', 'Advisory and market expansion services', 'Service period: Q4 2023', '', invoiceCitation.quote, '', 'Payment due within 14 days', 'Northstar Consulting GmbH'] },
  { id: 'doc-vendor', name: 'Vendor_master_export.pdf', type: 'Vendor master', language: 'DE', pages: 6, status: 'verified', extractedFacts: 94, previewLines: ['KREDITORenSTAMMDATEN', 'Exportdatum: 05.01.2024', '', 'Lieferant 49018', vendorCitation.quote, '', 'Status: Aktiv', 'Freigabestufe: A'] },
  { id: 'doc-ledger', name: 'General_ledger_Q4.xlsx.pdf', type: 'General ledger', language: 'DE', pages: 12, status: 'verified', extractedFacts: 387, previewLines: ['MERIDIAN PAYMENT SOLUTIONS GMBH', 'Hauptbuch · Geschäftsjahr 2023', '', 'Konto 1200 · Bankguthaben', ledgerCitation.quote, '', 'Kontrollsumme geprüft', 'Exportiert am 08.01.2024'] },
]

export const findings: FindingDetail[] = [
  { id: 'f-shared-iban', rank: 1, title: 'Supplier shares a bank account with cash confirmation', summary: 'An independent supplier and a trustee-held company account resolve to the same IBAN.', kind: 'finding', severity: 'critical', confidence: 98, reviewStatus: 'needs_review', amount: { amount: '2480000.00', currency: 'EUR', originalText: 'EUR 2,480,000', citation: invoiceCitation }, sourceCount: 3, citations: [bankCitation, invoiceCitation, vendorCitation], claim: 'Northstar Consulting GmbH received €2.48m through the same account used to substantiate Meridian’s reported cash balance.', checks: [{ label: 'IBAN equality', result: 'failed', detail: 'Exact canonical match across three independently classified documents.' }, { label: 'IBAN checksum', result: 'passed', detail: 'The account number passes ISO 13616 mod-97 validation.' }, { label: 'Party independence', result: 'failed', detail: 'Vendor master classifies Northstar as an external, unrelated supplier.' }], contradictions: [{ id: 'con-1', label: 'Bank confirmation', statement: 'The account supports Meridian’s cash balance.', citation: bankCitation }, { id: 'con-2', label: 'Supplier invoice', statement: 'The same account belongs to Northstar Consulting.', citation: invoiceCitation }, { id: 'con-3', label: 'Vendor master', statement: 'Northstar is recorded as an independent supplier.', citation: vendorCitation }], defenses: [{ explanation: 'Northstar may be a collection agent.', verdict: 'refuted', detail: 'No agency or collection agreement appears in the contract set.' }, { explanation: 'The IBAN may be a transcription error.', verdict: 'refuted', detail: 'The same IBAN appears in three source systems and passes checksum validation.' }] },
  { id: 'f-cash-gap', rank: 2, title: 'Cash confirmation does not tie to the ledger', summary: 'Confirmed balance exceeds the general ledger by €4.20m at the same reporting date.', kind: 'finding', severity: 'high', confidence: 96, reviewStatus: 'confirmed', amount: { amount: '4200000.00', currency: 'EUR', originalText: 'EUR 4,200,000', citation: bankCitation }, sourceCount: 2, citations: [bankCitation, ledgerCitation], claim: 'The bank confirmation and general ledger report incompatible year-end cash balances.', checks: [{ label: 'Reporting date', result: 'passed', detail: 'Both balances are dated 31 December 2023.' }, { label: 'Balance reconciliation', result: 'failed', detail: '€18.42m − €14.22m = €4.20m unexplained difference.' }], contradictions: [{ id: 'con-4', label: 'External confirmation', statement: 'Year-end balance is €18.42m.', citation: bankCitation }, { id: 'con-5', label: 'General ledger', statement: 'Year-end cash is €14.22m.', citation: ledgerCitation }], defenses: [{ explanation: 'Timing or cut-off difference.', verdict: 'refuted', detail: 'Both documents state the same reporting date; no reconciling items were supplied.' }] },
  { id: 'f-sequence', rank: 3, title: 'Invoice sequence gap requires review', summary: 'Seven invoice numbers are absent from an otherwise consecutive Q4 series.', kind: 'observation', severity: 'medium', confidence: 67, reviewStatus: 'needs_review', sourceCount: 1, citations: [invoiceCitation], claim: 'The Q4 invoice sequence contains an unexplained gap.', checks: [{ label: 'Sequence continuity', result: 'failed', detail: 'MPS-1041 through MPS-1047 are not present.' }], contradictions: [{ id: 'con-6', label: 'Invoice register', statement: 'Sequence resumes at MPS-1048.', citation: invoiceCitation }], defenses: [{ explanation: 'Invoices may have been voided.', verdict: 'plausible', detail: 'No void register was included in the dossier.' }] },
  { id: 'f-vat', rank: 4, title: 'VAT calculation reconciles', summary: 'Net amount, VAT rate, and gross payment agree within exact decimal arithmetic.', kind: 'clean', severity: 'low', confidence: 100, reviewStatus: 'rejected', sourceCount: 1, citations: [invoiceCitation], claim: 'No discrepancy was found in invoice tax arithmetic.', checks: [{ label: 'VAT recomputation', result: 'passed', detail: 'Net + 19% VAT equals the displayed gross amount.' }], contradictions: [], defenses: [] },
]

export const graph: GraphData = {
  nodes: [
    { id: 'meridian', label: 'Meridian Payments', kind: 'company', subtitle: 'Audited entity', risk: 'watch', sourceCount: 20, findingIds: ['f-shared-iban', 'f-cash-gap'], citations: [bankCitation, ledgerCitation] },
    { id: 'northstar', label: 'Northstar Consulting', kind: 'company', subtitle: 'External supplier', risk: 'alert', sourceCount: 3, findingIds: ['f-shared-iban'], citations: [invoiceCitation, vendorCitation] },
    { id: 'account', label: 'DE89 •••• 130 00', kind: 'account', subtitle: 'First Merchant Bank', risk: 'alert', sourceCount: 3, findingIds: ['f-shared-iban', 'f-cash-gap'], citations: [bankCitation, invoiceCitation, vendorCitation] },
    { id: 'trustee', label: 'Adrian Weiss', kind: 'person', subtitle: 'Trustee signatory', risk: 'watch', sourceCount: 2, findingIds: ['f-shared-iban'], citations: [bankCitation] },
    { id: 'cfo', label: 'Elena Kraus', kind: 'person', subtitle: 'Chief Financial Officer', risk: 'clear', sourceCount: 8, findingIds: [], citations: [ledgerCitation] },
    { id: 'bankdoc', label: 'Bank confirmation', kind: 'document', subtitle: '3 pages · verified', risk: 'watch', sourceCount: 1, findingIds: ['f-shared-iban', 'f-cash-gap'], citations: [bankCitation] },
  ],
  edges: [
    { id: 'e1', source: 'meridian', target: 'account', label: 'cash account', risk: 'watch', explanation: 'Reported as a trustee-held cash account for Meridian.', findingIds: ['f-shared-iban', 'f-cash-gap'], citations: [bankCitation] },
    { id: 'e2', source: 'northstar', target: 'account', label: 'same IBAN', risk: 'alert', explanation: 'Northstar invoices direct payment to Meridian’s confirmed cash account.', findingIds: ['f-shared-iban'], citations: [invoiceCitation, vendorCitation] },
    { id: 'e3', source: 'trustee', target: 'account', label: 'signatory', risk: 'watch', explanation: 'Named as trustee signatory on the bank confirmation.', findingIds: ['f-shared-iban'], citations: [bankCitation] },
    { id: 'e4', source: 'meridian', target: 'cfo', label: 'employs', risk: 'clear', explanation: 'CFO named in the general ledger approval record.', findingIds: [], citations: [ledgerCitation] },
    { id: 'e5', source: 'bankdoc', target: 'account', label: 'confirms', risk: 'watch', explanation: 'Document confirms the account and year-end balance.', findingIds: ['f-cash-gap'], citations: [bankCitation] },
  ],
}

